# general
gpu_id: 4
use_gpu: True

# multi-modal raw features
data_path: 'data/'
checkpoint_dir: 'saved'
save_recommended_topk: True
recommend_topk: 'recommend_topk/'

embedding_size: 64

# training settings
epochs: 1000
stopping_step: 30
train_batch_size: 2048
learner: adam
learning_rate: 0.0001
learning_rate_scheduler: [1.0, 50]
eval_step: 1

training_neg_sample_num: 1
use_neg_sampling: True
use_full_sampling: False
NEG_PREFIX: neg__


# evaluation settings
metrics: ["Recall", "NDCG", "Precision", "MAP"]
topk: [5, 10, 15, 20]
valid_metric: Recall@20
eval_batch_size: 4096

hyper_parameters: ["seed"]

embedding_size: 64
feat_embed_dim: 64


n_layers: 2
mm_image_weight: [0.5]
aggr_mode: ['add']
knn_k: [10]
k: [40]
n_mm_layers: [1]
learning_rate: [0.0001]
reg_weight: [0.01]
seed: [1009, 1107, 1210, 1104]
fusion: ["diffusion", "add", "pool", "Multi-Head Attention", "Transformer"]
hyper_parameters: ["seed", "fusion", "mm_image_weight", "k", "n_mm_layers", "knn_k", "aggr_mode", "reg_weight", "learning_rate"]